<!-- Copyright (C) 2009 The Libphonenumber Authors

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.

     @author: Shaopeng Jia

     Metadata on Phone Number Plan and formatting rules
     Note: Territories are in alphabetical order by their IDs, which are based on ISO 3166-1
           two-letter country codes (or are set to "001" for non-geographical entities, which
           represents "World" in the UN M.49 standard). The country names in the comments are the
           official short names in English according to ISO 3166-1.

     For more information on what each element represents, see
     resources/phonemetadata.proto

     Note that if you want to add validation metadata, the generalDesc nationalNumberPattern and
     possibleNumberPattern must be provided. If this is missing, then the country will be
     considered to have no more specific phone-number type metadata (fixedLine, mobile etc) and
     hence only basic validation rules (numbers should be between 3 and 15 digits long) will be
     applied.

     If adding an element for a non-geographical entity, please add an example number element to the
     general description.

     Country code, international and national prefix information main source:
     http://www.itu.int/pub/T-SP-E.164C-2011
-->

<!DOCTYPE phoneNumberMetadata [
    <!ELEMENT phoneNumberMetadata (territories)>
    <!ELEMENT territories (territory+)>
    <!ELEMENT territory (references?, availableFormats?, generalDesc?, noInternationalDialling?,
        areaCodeOptional?, fixedLine?, mobile?, pager?, tollFree?, premiumRate?,
        sharedCost?, personalNumber?, voip?, uan?, voicemail?)>
    <!ELEMENT references (sourceUrl+)>
    <!ELEMENT generalDesc (nationalNumberPattern, possibleNumberPattern, exampleNumber?)>
    <!ELEMENT noInternationalDialling (nationalNumberPattern, possibleNumberPattern?,
        exampleNumber?)>
    <!ELEMENT areaCodeOptional (nationalNumberPattern, possibleNumberPattern, exampleNumber?)>
    <!ELEMENT fixedLine (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT mobile (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT pager (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT tollFree (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT premiumRate (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT sharedCost (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT personalNumber (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT voip (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT uan (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT voicemail (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT sourceUrl (#PCDATA)>
    <!ELEMENT availableFormats (numberFormat+)>
    <!ELEMENT nationalNumberPattern (#PCDATA)>
    <!ELEMENT possibleNumberPattern (#PCDATA)>
    <!ELEMENT exampleNumber (#PCDATA)>
    <!ELEMENT numberFormat (leadingDigits*, format, intlFormat*)>
    <!ELEMENT format (#PCDATA)>
    <!ELEMENT intlFormat (#PCDATA)>
    <!ELEMENT leadingDigits (#PCDATA)>

    <!ATTLIST territory id CDATA #REQUIRED>
    <!ATTLIST territory countryCode CDATA #REQUIRED>
    <!ATTLIST territory mainCountryForCode (true) #IMPLIED>
    <!ATTLIST territory leadingDigits CDATA #IMPLIED>
    <!ATTLIST territory preferredInternationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory internationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixForParsing CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixTransformRule CDATA #IMPLIED>
    <!ATTLIST territory preferredExtnPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST territory leadingZeroPossible (true) #IMPLIED>
    <!ATTLIST territory carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory mobileNumberPortableRegion (true) #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST numberFormat carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat pattern CDATA #REQUIRED>
]>

<phoneNumberMetadata>
  <territories>
    <!-- Germany -->
    <territory id="DE" countryCode="49" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG"
               mobileNumberPortableRegion="true">
      <references>
        <sourceUrl>http://www.itu.int/oth/T0202000051/en</sourceUrl>
        <sourceUrl>http://en.wikipedia.org/wiki/Telephone_numbers_in_germany</sourceUrl>
      </references>
      <availableFormats>
        <!-- Mobile number formatting rules. We follow the ITU document here for guidance on how
             these should best be formatted, even though actual usage varies. -->
        <numberFormat pattern="(1\d{2})(\d{7,8})">
          <leadingDigits>1[67]</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(1\d{3})(\d{7})">
          <leadingDigits>15</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{3,11})">
          <leadingDigits>
            3[02]|
            40|
            [68]9
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- The order of the rules on 3-5 digits area code matter as fallback is used here. -->
        <!-- 3 digit area codes. -->
        <numberFormat pattern="(\d{3})(\d{3,11})">
          <leadingDigits>
            2(?:
              \d1|
              0[2389]|
              1[24]|
              28|
              34
            )|
            3(?:
              [3-9][15]|
              40
            )|
            [4-8][1-9]1|
            9(?:
              06|
              [1-9]1
            )
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- 4 digit area codes. -->
        <numberFormat pattern="(\d{4})(\d{2,11})">
          <leadingDigits>
            [24-6]|
            [7-9](?:
              \d[1-9]|
              [1-9]\d
            )|
            3(?:
              [3569][02-46-9]|
              4[2-4679]|
              7[2-467]|
              8[2-46-8]
            )
          </leadingDigits>
          <leadingDigits>
            [24-6]|
            [7-9](?:
              \d[1-9]|
              [1-9]\d
            )|
            3(?:
              3(?:
                0[1-467]|
                2[127-9]|
                3[124578]|
                [46][1246]|
                7[1257-9]|
                8[1256]|
                9[145]
              )|
              4(?:
                2[135]|
                3[1357]|
                4[13578]|
                6[1246]|
                7[1356]|
                9[1346]
              )|
              5(?:
                0[14]|
                2[1-3589]|
                3[1357]|
                4[1246]|
                6[1-4]|
                7[1346]|
                8[13568]|
                9[1246]
              )|
              6(?:
                0[356]|
                2[1-489]|
                3[124-6]|
                4[1347]|
                6[13]|
                7[12579]|
                8[1-356]|
                9[135]
              )|
              7(?:
                2[1-7]|
                3[1357]|
                4[145]|
                6[1-5]|
                7[1-4]
              )|
              8(?:
                21|
                3[1468]|
                4[1347]|
                6[0135-9]|
                7[1467]|
                8[136]
              )|
              9(?:
                0[12479]|
                2[1358]|
                3[1357]|
                4[134679]|
                6[1-9]|
                7[136]|
                8[147]|
                9[1468]
              )
            )
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- 5 digit area codes. -->
        <numberFormat pattern="(3\d{4})(\d{1,10})">
          <leadingDigits>3</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- Note: this is getting ridiculous! How can we format these better? -->
        <numberFormat pattern="(800)(\d{7,12})">
          <leadingDigits>800</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- Voicemail access numbers for the carrier Blau. -->
        <numberFormat pattern="(177)(99)(\d{7,8})">
          <leadingDigits>177</leadingDigits>
          <leadingDigits>1779</leadingDigits>
          <leadingDigits>17799</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d)(\d{4,10})">
          <leadingDigits>
            (?:
              18|
              90
            )0|
            137
          </leadingDigits>
          <leadingDigits>
            1(?:
              37|
              80
            )|
            900[1359]
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(1\d{2})(\d{5,11})">
          <leadingDigits>181</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- Where we have seen prefixes in use for the IVPN/User Group numbers, we format it the
             way it is generally written. For other prefixes, we fall back to using a three-digit
             prefix since we have currently no more information to allow us to format these more
             precisely. -->
        <numberFormat pattern="(18\d{3})(\d{6})">
          <leadingDigits>185</leadingDigits>
          <leadingDigits>1850</leadingDigits>
          <leadingDigits>18500</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(18\d{2})(\d{7})">
          <leadingDigits>18[68]</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(18\d)(\d{8})">
          <leadingDigits>18[2-579]</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(700)(\d{4})(\d{4})">
          <leadingDigits>700</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(138)(\d{4})">
          <leadingDigits>138</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <!-- When deciding whether to assume a leading 49 is a country code or not, the number is
             examined to see if it is valid with the 49 as part of the number. Due to the variable
             length of German numbers, this test is hard to do. The national pattern is hence
             stricter for numbers starting with 49, to try and remove the country code if the number
             begins with 49 whenever possible. -->
        <nationalNumberPattern>
          [1-35-9]\d{3,14}|
          4(?:
            [0-8]\d{4,12}|
            9(?:
              [0-37]\d|
              4(?:
                [1-35-8]|
                4\d?
              )|
              5\d{1,2}|
              6[1-8]\d?
            )\d{2,7}
          )
        </nationalNumberPattern>
        <possibleNumberPattern>\d{2,15}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <!-- The numbering plan defines rather optimistic longest-number limits - online numbers
             don't seem to respect this. The max-length is hence extended. -->
        <nationalNumberPattern>
          [246]\d{5,13}|
          3(?:
            0\d{3,13}|
            2\d{9}|
            [3-9]\d{4,13}
          )|
          5(?:
            0[2-8]|
            [1256]\d|
            [38][0-8]|
            4\d{0,2}|
            [79][0-7]
          )\d{3,11}|
          7(?:
            0[2-8]|
            [1-9]\d
          )\d{3,10}|
          8(?:
            0[2-9]|
            [1-9]\d
          )\d{3,10}|
          9(?:
            0[6-9]\d{3,10}|
            1\d{4,12}|
            [2-9]\d{4,11}
          )
        </nationalNumberPattern>
        <exampleNumber>30123456</exampleNumber>
      </fixedLine>
      <mobile>
        <!-- According to
             http://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/BNetzA/Sachgebiete/Telekommunikation/Regulierung/Nummernverwaltung/Mobilfunkdienste/NummernplanMobileDienstepdf.pdf?__blob=publicationFile
             numbers beginning with 162, 163 and 17 can all be 10 or 11 digits long.
             The ranges 15[056] have been removed from the ITU doc, but information found online
             indicates that they may still be working.
             -->
        <nationalNumberPattern>
          1(?:
            5[0-2579]\d{8}|
            6[023]\d{7,8}|
            7(?:
              [0-57-9]\d?|
              6\d
            )\d{7}
          )
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10,11}</possibleNumberPattern>
        <exampleNumber>15123456789</exampleNumber>
      </mobile>
      <pager>
        <nationalNumberPattern>
          16(?:
            4\d{1,10}|
            [89]\d{1,11}
          )
        </nationalNumberPattern>
        <possibleNumberPattern>\d{4,14}</possibleNumberPattern>
        <exampleNumber>16412345</exampleNumber>
      </pager>
      <tollFree>
        <nationalNumberPattern>800\d{7,12}</nationalNumberPattern>
        <possibleNumberPattern>\d{10,15}</possibleNumberPattern>
        <exampleNumber>8001234567890</exampleNumber>
      </tollFree>
      <premiumRate>
        <!-- Includes the more expensive of the "televoting" line numbers. See the shared cost
             section for more information. -->
        <nationalNumberPattern>
          137[7-9]\d{6}|
          900(?:
            [135]\d{6}|
            9\d{7}
          )
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10,11}</possibleNumberPattern>
        <exampleNumber>9001234567</exampleNumber>
      </premiumRate>
      <sharedCost>
        <!-- Includes some mass-traffic numbers, used for e.g. phone voting, raffles, since their
             costs when dialling from a fixed-line phone is similar.
             Prices:
             http://www.billiger-telefonieren.de/0180-0137-0900-sonderrufnummern/
             Documentation:
             http://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Nummerierung/Rufnummern/0137/0137_Nummernplan.pdf?__blob=publicationFile&v=2
        -->
        <nationalNumberPattern>
          1(?:
            3(?:
              7[1-6]\d{6}|
              8\d{4}
            )|
            80\d{5,11}
          )
        </nationalNumberPattern>
        <possibleNumberPattern>\d{7,14}</possibleNumberPattern>
        <exampleNumber>18012345</exampleNumber>
      </sharedCost>
      <personalNumber>
        <nationalNumberPattern>700\d{8}</nationalNumberPattern>
        <possibleNumberPattern>\d{11}</possibleNumberPattern>
        <exampleNumber>70012345678</exampleNumber>
      </personalNumber>
      <uan>
        <!-- Using UAN for numbers marked in the plan as being assigned to International Virtual
             Private Networks (0181) & User Groups (018[2-9]). These seem in practice to be assigned
             to companies. More information here: http://de.wikipedia.org/wiki/Vorwahl_01 -->
        <nationalNumberPattern>
          18(?:
            1\d{5,11}|
            [2-9]\d{8}
          )
        </nationalNumberPattern>
        <possibleNumberPattern>\d{8,14}</possibleNumberPattern>
        <exampleNumber>18500123456</exampleNumber>
      </uan>
      <voicemail>
        <nationalNumberPattern>17799\d{7,8}</nationalNumberPattern>
        <possibleNumberPattern>\d{12,13}</possibleNumberPattern>
        <exampleNumber>177991234567</exampleNumber>
      </voicemail>
    </territory>
    
    
        <!-- Austria -->
    <territory id="AT" countryCode="43" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG"
               mobileNumberPortableRegion="true">
      <references>
        <sourceUrl>http://www.rtr.at/en/tk/E129</sourceUrl>
      </references>
      <availableFormats>
        <numberFormat pattern="(1)(\d{3,12})">
          <leadingDigits>1</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <!-- The following three patterns are the most common for prefixes 050, 057 and 059, as
             found on Austrian web pages. -->
        <numberFormat pattern="(5\d)(\d{3,5})">
          <leadingDigits>5[079]</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(5\d)(\d{3})(\d{3,4})">
          <leadingDigits>5[079]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(5\d)(\d{4})(\d{4,7})">
          <leadingDigits>5[079]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{3,10})">
          <leadingDigits>
            316|
            46|
            51|
            732|
            6(?:
              44|
              5[0-3579]|
              [6-9]
            )|
            7(?:
              1|
              [28]0
            )|
            [89]
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(\d{4})(\d{3,9})">
          <leadingDigits>
            2|
            3(?:
              1[1-578]|
              [3-8]
            )|
            4[2378]|
            5[2-6]|
            6(?:
              [12]|
              4[1-35-9]|
              5[468]
            )|
            7(?:
              2[1-8]|
              35|
              4[1-8]|
              [5-79]
            )
          </leadingDigits>
            <format>$1 $2</format>
          </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[1-9]\d{3,12}</nationalNumberPattern>
        <possibleNumberPattern>\d{3,13}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <!-- Note that the full area code is not validated - just the first 3 digits. This also
             means that even though for most Austrian numbers the minimum length is 7, we allow 6
             since we don't differentiate below between 3 and 4 digit area codes for reasons of
             efficiency. -->
        <nationalNumberPattern>
          1\d{3,12}|
          (?:
            2(?:
              1[467]|
              2[13-8]|
              5[2357]|
              6[1-46-8]|
              7[1-8]|
              8[124-7]|
              9[1458]
            )|
            3(?:
              1[1-8]|
              3[23568]|
              4[5-7]|
              5[1378]|
              6[1-38]|
              8[3-68]
            )|
            4(?:
              2[1-8]|
              35|
              63|
              7[1368]|
              8[2457]
            )|
            5(?:
              12|
              2[1-8]|
              3[357]|
              4[147]|
              5[12578]|
              6[37]
            )|
            6(?:
              13|
              2[1-47]|
              4[1-35-8]|
              5[468]|
              62
            )|
            7(?:
              2[1-8]|
              3[25]|
              4[13478]|
              5[68]|
              6[16-8]|
              7[1-6]|
              9[45]
            )
          )\d{3,10}
        </nationalNumberPattern>
        <exampleNumber>1234567890</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>
          6(?:
            44|
            5[0-3579]|
            6[013-9]|
            [7-9]\d
          )\d{4,10}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{7,13}</possibleNumberPattern>
        <exampleNumber>644123456</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>80[02]\d{6,10}</nationalNumberPattern>
        <possibleNumberPattern>\d{9,13}</possibleNumberPattern>
        <exampleNumber>800123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>
          (?:
            711|
            9(?:
              0[01]|
              3[019]
            )
          )\d{6,10}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{9,13}</possibleNumberPattern>
        <exampleNumber>900123456</exampleNumber>
      </premiumRate>
      <sharedCost>
        <nationalNumberPattern>
          8(?:
            10|
            2[018]
          )\d{6,10}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{9,13}</possibleNumberPattern>
        <exampleNumber>810123456</exampleNumber>
      </sharedCost>
      <voip>
        <nationalNumberPattern>780\d{6,10}</nationalNumberPattern>
        <possibleNumberPattern>\d{9,13}</possibleNumberPattern>
        <exampleNumber>780123456</exampleNumber>
      </voip>
      <uan>
        <nationalNumberPattern>
          5(?:
            (?:
              0[1-9]|
              17
            )\d{2,10}|
            [79]\d{3,11}
          )|
          720\d{6,10}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{5,13}</possibleNumberPattern>
        <exampleNumber>50123</exampleNumber>
      </uan>
    </territory>
    
        <!-- Switzerland -->
    <territory id="CH" countryCode="41" internationalPrefix="00"
               nationalPrefix="0"  nationalPrefixFormattingRule="$NP$FG"
               mobileNumberPortableRegion="true">
      <references>
        <!-- Under Technical prescriptions: Numbering plan for international carriers. -->
        <sourceUrl>http://www.bakom.admin.ch/themen/telekom/00479/00604/index.html?lang=en</sourceUrl>
      </references>
      <availableFormats>
        <numberFormat pattern="([2-9]\d)(\d{3})(\d{2})(\d{2})">
          <leadingDigits>
            [2-7]|
            [89]1
          </leadingDigits>
          <format>$1 $2 $3 $4</format>
        </numberFormat>
        <numberFormat pattern="([89]\d{2})(\d{3})(\d{3})">
          <leadingDigits>
            8[047]|
            90
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{2})(\d{3})(\d{2})(\d{2})">
          <leadingDigits>860</leadingDigits>
          <format>$1 $2 $3 $4 $5</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          [2-9]\d{8}|
          860\d{9}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{9}(?:\d{3})?</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>
          (?:
            2[12467]|
            3[1-4]|
            4[134]|
            5[256]|
            6[12]|
            [7-9]1
          )\d{7}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>212345678</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>7[5-9]\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>781234567</exampleNumber>
      </mobile>
      <pager>
        <!-- https://www.eofcom.admin.ch/eofcom/public/listEofcom_e164Allocated.do -->
        <nationalNumberPattern>74[0248]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>740123456</exampleNumber>
      </pager>
      <tollFree>
        <nationalNumberPattern>800\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>800123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>90[016]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>900123456</exampleNumber>
      </premiumRate>
      <sharedCost>
        <nationalNumberPattern>84[0248]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>840123456</exampleNumber>
      </sharedCost>
      <personalNumber>
        <nationalNumberPattern>878\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>878123456</exampleNumber>
      </personalNumber>
      <uan>
        <!-- Used for corporate networks. -->
        <nationalNumberPattern>5[18]\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>581234567</exampleNumber>
      </uan>
      <voicemail>
        <nationalNumberPattern>860\d{9}</nationalNumberPattern>
        <possibleNumberPattern>\d{12}</possibleNumberPattern>
        <exampleNumber>860123456789</exampleNumber>
      </voicemail>
    </territory>
  </territories>
</phoneNumberMetadata>
